package com.faktorzehn.socialNetwork.model.pojo;

import com.fasterxml.jackson.annotation.*;
import lombok.Data;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Data
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.StringIdGenerator.class, property="autogeneratedUUID") //preventing infinite recursive call of getFriends
public class User implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    private String username;

    @ManyToMany(cascade = CascadeType.ALL)
    @ToString.Exclude
    private List<User> listOfFriends;
    @ManyToMany(cascade = CascadeType.ALL)
    @ToString.Exclude
    private List<Message> outboundMessages;
    @ManyToMany(cascade = CascadeType.ALL)
    @ToString.Exclude
    private List<Message> inboundMessages;

    public User (String username){

        this.username = username;
        this.listOfFriends = new ArrayList<>();
        this.outboundMessages = new ArrayList<>();
        this.inboundMessages = new ArrayList<>();

    }
    public User(){

    }

}

